export const DEFAULT_PRODUCT_CATEGORY = "Clothing";

export const PRODUCT_CATEGORIES = [
  "Clothing",
  "T-Shirts",
  "Graphic T-Shirts",
  "Tank Tops",
  "Crop Tops",
  "Blouses",
  "Shirts",
  "Dress Shirts",
  "Polo Shirts",
  "Tunics",
  "Hoodies",
  "Sweatshirts",
  "Sweaters",
  "Cardigans",
  "Pullovers",
  "Vests",
  "Jackets",
  "Denim Jackets",
  "Leather Jackets",
  "Bomber Jackets",
  "Puffer Jackets",
  "Windbreakers",
  "Coats",
  "Trench Coats",
  "Parkas",
  "Blazers",
  "Suits",
  "Tuxedos",
  "Waistcoats",
  "Jeans",
  "Trousers",
  "Chinos",
  "Cargo Pants",
  "Leggings",
  "Joggers",
  "Track Pants",
  "Shorts",
  "Denim Shorts",
  "Skirts",
  "Mini Skirts",
  "Midi Skirts",
  "Maxi Skirts",
  "Dresses",
  "Mini Dresses",
  "Midi Dresses",
  "Maxi Dresses",
  "Cocktail Dresses",
  "Evening Dresses",
  "Gowns",
  "Jumpsuits",
  "Rompers",
  "Overalls",
  "Co-ord Sets",
  "Sarees",
  "Blouses for Sarees",
  "Salwar Kameez",
  "Kurtas",
  "Kurtis",
  "Lehenga",
  "Sherwani",
  "Nehru Jackets",
  "Dhoti",
  "Ethnic Wear",
  "Traditional Wear",
  "Tracksuits",
  "Activewear",
  "Sportswear",
  "Gym Wear",
  "Yoga Wear",
  "Cycling Wear",
  "Running Wear",
  "Sports Jerseys",
  "Loungewear",
  "Sleepwear",
  "Pajamas",
  "Robes",
  "Innerwear",
  "Bras",
  "Briefs",
  "Boxers",
  "Shapewear",
  "Thermal Wear",
  "Swimwear",
  "Bikinis",
  "Swimsuits",
  "Board Shorts",
  "Beachwear",
  "Shoes",
  "Sneakers",
  "Running Shoes",
  "Formal Shoes",
  "Loafers",
  "Sandals",
  "Slippers",
  "Flip-Flops",
  "Boots",
  "Ankle Boots",
  "Heels",
  "Flats",
  "Wedges",
  "Bags",
  "Handbags",
  "Shoulder Bags",
  "Tote Bags",
  "Crossbody Bags",
  "Backpacks",
  "Clutches",
  "Wallets",
  "Belts",
  "Caps",
  "Hats",
  "Beanies",
  "Scarves",
  "Shawls",
  "Gloves",
  "Socks",
  "Tights",
  "Watches",
  "Jewelry",
  "Necklaces",
  "Earrings",
  "Bracelets",
  "Rings",
  "Sunglasses",
  "Eyewear",
  "Hair Accessories",
  "Ties",
  "Bow Ties",
  "Pocket Squares",
  "Kidswear",
  "Boys Clothing",
  "Girls Clothing",
  "School Wear",
  "School Uniforms",
  "Babywear",
  "Baby Bodysuits",
  "Formalwear",
  "Business Wear",
  "Casualwear",
  "Smart Casual",
  "Streetwear",
  "Party Wear",
  "Wedding Wear",
  "Bridal Wear",
  "Winter Wear",
  "Summer Wear",
  "Rainwear",
  "Uniforms",
  "Work Uniforms",
  "Workwear",
  "Plus Size Clothing",
  "Petite Clothing",
  "Tall Clothing",
  "Maternity Wear",
  "Nursing Wear",
  "Adaptive Clothing",
  "Modest Wear",
  "Sustainable Fashion",
  "Vintage Clothing",
  "Costumes",
  "Accessories"
];

export function isProductCategory(value) {
  return PRODUCT_CATEGORIES.includes(value);
}
